project_id = "jsubmkwvqzddgppvgxiu"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = false

[functions.portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.test]
verify_jwt = false