// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jsubmkwvqzddgppvgxiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzdWJta3d2cXpkZGdwcHZneGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTA1NDQsImV4cCI6MjA3MDUyNjU0NH0.iamBB3vgWkHfX6vl5WTMdOS-6Varh3dWZ1Nmn18nsOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});